package com.chirui.reader.ui.theme

import androidx.compose.ui.graphics.Color

/**
 * Kotatsu exact color palette from colors_kotatsu.xml
 * M3 colors generated by Material Theme Builder
 * 
 * Primary: Blue (#0059C8)
 * Default light/dark themes matching Kotatsu's design
 */

// Kotatsu Primary Colors (Blue theme)
val KotatsuPrimary = Color(0xFF0059C8)
val KotatsuPrimaryContainer = Color(0xFFD9E2FF)
val KotatsuOnPrimary = Color(0xFFFFFFFF)
val KotatsuOnPrimaryContainer = Color(0xFF001944)
val KotatsuInversePrimary = Color(0xFFAFC6FF)

// Kotatsu Secondary Colors
val KotatsuSecondary = Color(0xFF575E71)
val KotatsuSecondaryContainer = Color(0xFFDBE2F9)
val KotatsuOnSecondary = Color(0xFFFFFFFF)
val KotatsuOnSecondaryContainer = Color(0xFF141B2C)

// Kotatsu Tertiary Colors  
val KotatsuTertiary = Color(0xFF725573)
val KotatsuTertiaryContainer = Color(0xFFFDD7FB)
val KotatsuOnTertiary = Color(0xFFFFFFFF)
val KotatsuOnTertiaryContainer = Color(0xFF2A132C)

// Kotatsu Surface Colors (Light)
val KotatsuSurface = Color(0xFFFBF8FD)
val KotatsuSurfaceDim = Color(0xFFDBD9DD)
val KotatsuSurfaceBright = Color(0xFFFBF8FD)
val KotatsuSurfaceContainerLowest = Color(0xFFFFFFFF)
val KotatsuSurfaceContainerLow = Color(0xFFF5F3F7)
val KotatsuSurfaceContainer = Color(0xFFEFEDF1)
val KotatsuSurfaceContainerHigh = Color(0xFFE9E7EC)
val KotatsuSurfaceContainerHighest = Color(0xFFE3E2E6)
val KotatsuSurfaceVariant = Color(0xFFE1E2EC)
val KotatsuOnSurface = Color(0xFF1B1B1F)
val KotatsuOnSurfaceVariant = Color(0xFF44464F)
val KotatsuInverseSurface = Color(0xFF303034)
val KotatsuInverseOnSurface = Color(0xFFF2F0F4)
val KotatsuBackground = Color(0xFFFEFBFF)
val KotatsuOutline = Color(0xFF757780)

// Error Colors (from Kotatsu)
val KotatsuError = Color(0xFFBA1B1B)
val KotatsuErrorContainer = Color(0xFFFFDAD4)
val KotatsuOnError = Color(0xFFFFFFFF)
val KotatsuOnErrorContainer = Color(0xFF410001)

// Dark theme colors (Material 3 dark counterparts)
val KotatsuPrimaryDark = Color(0xFFAFC6FF)
val KotatsuPrimaryContainerDark = Color(0xFF00429A)
val KotatsuOnPrimaryDark = Color(0xFF002D6E)
val KotatsuOnPrimaryContainerDark = Color(0xFFD9E2FF)

val KotatsuSecondaryDark = Color(0xFFBFC6DC)
val KotatsuSecondaryContainerDark = Color(0xFF404659)
val KotatsuOnSecondaryDark = Color(0xFF293042)
val KotatsuOnSecondaryContainerDark = Color(0xFFDBE2F9)

val KotatsuTertiaryDark = Color(0xFFE0BBDE)
val KotatsuTertiaryContainerDark = Color(0xFF593D5A)
val KotatsuOnTertiaryDark = Color(0xFF412743)
val KotatsuOnTertiaryContainerDark = Color(0xFFFDD7FB)

val KotatsuSurfaceDark = Color(0xFF131316)
val KotatsuSurfaceVariantDark = Color(0xFF44464F)
val KotatsuOnSurfaceDark = Color(0xFFE3E2E6)
val KotatsuOnSurfaceVariantDark = Color(0xFFC5C6D0)
val KotatsuOutlineDark = Color(0xFF8F9099)

val KotatsuErrorDark = Color(0xFFFFB4AB)
val KotatsuErrorContainerDark = Color(0xFF93000A)
val KotatsuOnErrorDark = Color(0xFF690005)
val KotatsuOnErrorContainerDark = Color(0xFFFFDAD6)

/**
 * Light color scheme matching Kotatsu's default theme
 */
val LightColorScheme = androidx.compose.material3.lightColorScheme(
    primary = KotatsuPrimary,
    onPrimary = KotatsuOnPrimary,
    primaryContainer = KotatsuPrimaryContainer,
    onPrimaryContainer = KotatsuOnPrimaryContainer,
    inversePrimary = KotatsuInversePrimary,
    secondary = KotatsuSecondary,
    onSecondary = KotatsuOnSecondary,
    secondaryContainer = KotatsuSecondaryContainer,
    onSecondaryContainer = KotatsuOnSecondaryContainer,
    tertiary = KotatsuTertiary,
    onTertiary = KotatsuOnTertiary,
    tertiaryContainer = KotatsuTertiaryContainer,
    onTertiaryContainer = KotatsuOnTertiaryContainer,
    background = KotatsuBackground,
    onBackground = KotatsuOnSurface,
    surface = KotatsuSurface,
    onSurface = KotatsuOnSurface,
    surfaceVariant = KotatsuSurfaceVariant,
    onSurfaceVariant = KotatsuOnSurfaceVariant,
    surfaceTint = KotatsuPrimary,
    inverseSurface = KotatsuInverseSurface,
    inverseOnSurface = KotatsuInverseOnSurface,
    error = KotatsuError,
    onError = KotatsuOnError,
    errorContainer = KotatsuErrorContainer,
    onErrorContainer = KotatsuOnErrorContainer,
    outline = KotatsuOutline,
    outlineVariant = KotatsuOutline,
    scrim = Color.Black
)

/**
 * Dark color scheme matching Kotatsu's dark theme
 */
val DarkColorScheme = androidx.compose.material3.darkColorScheme(
    primary = KotatsuPrimaryDark,
    onPrimary = KotatsuOnPrimaryDark,
    primaryContainer = KotatsuPrimaryContainerDark,
    onPrimaryContainer = KotatsuOnPrimaryContainerDark,
    inversePrimary = KotatsuPrimary,
    secondary = KotatsuSecondaryDark,
    onSecondary = KotatsuOnSecondaryDark,
    secondaryContainer = KotatsuSecondaryContainerDark,
    onSecondaryContainer = KotatsuOnSecondaryContainerDark,
    tertiary = KotatsuTertiaryDark,
    onTertiary = KotatsuOnTertiaryDark,
    tertiaryContainer = KotatsuTertiaryContainerDark,
    onTertiaryContainer = KotatsuOnTertiaryContainerDark,
    background = KotatsuSurfaceDark,
    onBackground = KotatsuOnSurfaceDark,
    surface = KotatsuSurfaceDark,
    onSurface = KotatsuOnSurfaceDark,
    surfaceVariant = KotatsuSurfaceVariantDark,
    onSurfaceVariant = KotatsuOnSurfaceVariantDark,
    surfaceTint = KotatsuPrimaryDark,
    inverseSurface = KotatsuOnSurfaceDark,
    inverseOnSurface = KotatsuSurfaceDark,
    error = KotatsuErrorDark,
    onError = KotatsuOnErrorDark,
    errorContainer = KotatsuErrorContainerDark,
    onErrorContainer = KotatsuOnErrorContainerDark,
    outline = KotatsuOutlineDark,
    outlineVariant = KotatsuOutlineDark,
    scrim = Color.Black
)
